# Generated by Django 5.1.4 on 2026-04-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='salesplan',
            options={'ordering': ['-period_start'], 'verbose_name': 'Sales Plan', 'verbose_name_plural': 'Sales Plans'},
        ),
    ]
