# Generated by Django 5.1.4 on 2026-04-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_options_alter_role_options_and_more'),
        ('workspaces', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='workspaces.workspace'),
        ),
    ]
