# Generated by Django 5.1.4 on 2026-04-15 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('deals_count', 'Количество сделок'), ('revenue_usd', 'Выручка USD'), ('new_leads', 'Новые лиды'), ('tasks_done', 'Задачи выполнены'), ('clients_added', 'Новые клиенты')], max_length=30)),
                ('period', models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('period_number', models.PositiveIntegerField()),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Target',
                'verbose_name_plural': 'KPI Targets',
                'ordering': ['-year', '-period_number', 'metric'],
                'unique_together': {('assigned_to', 'metric', 'period', 'year', 'period_number')},
            },
        ),
    ]
