# Generated by Django 5.1.4 on 2026-04-15 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpitarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='kpitarget',
            unique_together={('assigned_to', 'department', 'metric', 'period', 'year', 'period_number')},
        ),
    ]
