# Generated by Django 5.1.4 on 2026-04-23 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_kpitarget_unique_together_kpitarget_department_and_more'),
        ('workspaces', '0003_seed_default_idev'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitarget',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
    ]
