# Generated by Django 5.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_contact_order_contact_role_contact_telegram_and_more'),
        ('deals', '0002_dealdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                (
                    'event_type',
                    models.CharField(
                        choices=[('meeting', 'Встреча'), ('call', 'Звонок'), ('other', 'Другое')],
                        default='other',
                        max_length=20,
                    ),
                ),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'assigned_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'linked_client',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='calendar_events',
                        to='clients.client',
                    ),
                ),
                (
                    'linked_deal',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='calendar_events',
                        to='deals.deal',
                    ),
                ),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
