# Generated by Django 5.1.4 on 2026-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, choices=[('decision_maker', 'ЛПР'), ('manager', 'Менеджер'), ('secretary', 'Секретарь'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
