# Generated by Django 5.1.4 on 2026-04-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ba', 'Business Analyst'), ('sa', 'System Analyst'), ('dev_junior', 'Developer — Junior'), ('dev_middle', 'Developer — Middle'), ('dev_senior', 'Developer — Senior'), ('dev_lead', 'Developer — Lead'), ('qa', 'QA Engineer'), ('devops', 'DevOps'), ('pm', 'Project Manager'), ('other', 'Other')], max_length=30)),
                ('role_custom', models.CharField(blank=True, help_text='Free-form role name when role=other', max_length=100)),
                ('unit', models.CharField(choices=[('hourly', 'Per hour'), ('monthly', 'Per month')], default='monthly', max_length=10)),
                ('bill_rate_usd', models.DecimalField(decimal_places=2, help_text='What we bill the client', max_digits=10)),
                ('cost_rate_usd', models.DecimalField(decimal_places=2, default=0, help_text='Internal cost (consultant payroll + overhead)', max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='clients.client')),
            ],
            options={
                'ordering': ['client', 'role'],
                'unique_together': {('client', 'role', 'role_custom', 'unit')},
            },
        ),
    ]
