# Generated by Django 5.1.4 on 2026-04-16 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_ratecard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='[{code, weight, detail}] — explainability'),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100, higher = riskier'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, help_text='ИНН / TIN (digits only; 10 for RU legal entity, 12 for RU IP)', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id_country',
            field=models.CharField(blank=True, default='', help_text='ISO-3166 alpha-2, e.g. RU', max_length=2),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tax_id'], name='clients_cli_tax_id_f962f3_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['risk_score'], name='clients_cli_risk_sc_6a75ca_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['risk_level'], name='clients_cli_risk_le_fa745a_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('tax_id_country', 'tax_id'), name='unique_tax_id_per_country'),
        ),
    ]
