# Generated by Django 5.1.4 on 2026-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_risk_factors_client_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sync_data',
            field=models.JSONField(blank=True, default=dict, help_text='{enriched: {...}, egrul: {...}, financials: {...}, hh: {...}}'),
        ),
        migrations.AddField(
            model_name='client',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sync_status',
            field=models.CharField(default='', help_text='pending / in_progress / done / failed', max_length=20),
        ),
    ]
