# Generated by Django 5.1.4 on 2026-04-23 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_seed_default_idev'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('task', 'Task'), ('stage_change', 'Stage Change'), ('field_change', 'Field Change'), ('created', 'Created'), ('ai', 'AI')], max_length=20)),
                ('entity', models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal'), ('client', 'Client')], max_length=10)),
                ('entity_id', models.PositiveIntegerField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('meta', models.JSONField(default=dict)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['entity', 'entity_id', '-created_at'], name='act_entity_created_idx'), models.Index(fields=['workspace', 'type', 'due_at'], name='act_ws_type_due_idx')],
            },
        ),
    ]
