# Generated by Django 5.1.4 on 2026-04-23 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_seed_default_idev'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('client', 'Client'), ('deal', 'Deal'), ('lead', 'Lead')], max_length=20)),
                ('code', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Datetime'), ('boolean', 'Boolean'), ('enum', 'Enum'), ('multi_enum', 'Multi Enum'), ('url', 'URL'), ('email', 'Email')], default='string', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_defs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['entity', 'order', 'label'],
                'unique_together': {('workspace', 'entity', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('client', 'Client'), ('deal', 'Deal'), ('lead', 'Lead')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_fields.customfielddef')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='custom_fiel_entity_3acfc8_idx')],
                'unique_together': {('field', 'entity', 'entity_id')},
            },
        ),
    ]
