# Generated by Django 5.1.4 on 2026-04-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_dealdocument'),
        ('workspaces', '0003_seed_default_idev'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='dealnote',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
    ]
