# Generated by Django 5.1.4 on 2026-04-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_workspace_not_null'),
        ('pipelines', '0002_seed_default_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='pipelines.pipeline'),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='pipelines.stage'),
        ),
    ]
