# Generated by Django 5.1.4 on 2026-04-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_backfill_stage_from_status'),
        ('dictionaries', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lost_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dictionaries.lostreason'),
        ),
        migrations.AddField(
            model_name='deal',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dictionaries.source'),
        ),
    ]
