# Generated by Django 5.1.4 on 2026-04-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_workspace_not_null'),
        ('deals', '0008_add_source_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amount_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='When set, overrides the auto-sum of DealItem subtotals.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_type', models.CharField(choices=[('monthly', 'Monthly'), ('hourly', 'Hourly'), ('fixed', 'Fixed')], default='monthly', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('months', models.PositiveIntegerField(default=1)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deals.deal')),
                ('ratecard_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_items', to='clients.ratecard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
