# Generated by Django 5.1.4 on 2026-04-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_add_dealitem_amount_override'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_items', to='products.product'),
        ),
    ]
