# Generated by Django 5.1.4 on 2026-04-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_seed_default_idev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.SlugField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (шт, мес, час, etc.)', max_length=32)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_rate_type', models.CharField(blank=True, help_text="'monthly', 'hourly', or 'fixed'", max_length=8)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sku__gt', '')), fields=('workspace', 'sku'), name='unique_product_sku_per_workspace')],
            },
        ),
    ]
