# Generated by Django 5.1.4 on 2026-04-23 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_seed_default_idev'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lead', 'Лид'), ('deal', 'Сделка')], max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['kind', 'order', 'name'],
                'unique_together': {('workspace', 'kind', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=64)),
                ('semantic', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('converted', 'Converted')], default='open', max_length=16)),
                ('color', models.CharField(default='#6B7280', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pipelines.pipeline')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('pipeline', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal')], max_length=8)),
                ('entity_id', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pipelines.stage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipelines.stage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'at'], name='pipelines_s_entity__458fc8_idx')],
            },
        ),
    ]
