# Generated by Django 5.1.4 on 2026-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_seed_default_pipeline'),
        ('workspaces', '0003_seed_default_idev'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('workspace', 'kind'), name='unique_default_pipeline_per_workspace_kind'),
        ),
    ]
